// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUohPXLMt25O1U7Kfc8xf2MwYZC1zqCl0',
    appId: '1:746604535148:web:b953ad454d49b1324ae749',
    messagingSenderId: '746604535148',
    projectId: 'flordle-tpsi2526',
    authDomain: 'flordle-tpsi2526.firebaseapp.com',
    storageBucket: 'flordle-tpsi2526.firebasestorage.app',
    measurementId: 'G-N0J3E2YCSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsO3X73hFu65N4-TtHZXyom9JQZxap2Ac',
    appId: '1:746604535148:android:01436941a0b8a5634ae749',
    messagingSenderId: '746604535148',
    projectId: 'flordle-tpsi2526',
    storageBucket: 'flordle-tpsi2526.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJlgSl6cQzlbv5P91Dxw-fKxmKAQCYO8k',
    appId: '1:746604535148:ios:60f721dfd0a30ba84ae749',
    messagingSenderId: '746604535148',
    projectId: 'flordle-tpsi2526',
    storageBucket: 'flordle-tpsi2526.firebasestorage.app',
    iosBundleId: 'com.example.projetoProgMobileWordle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJlgSl6cQzlbv5P91Dxw-fKxmKAQCYO8k',
    appId: '1:746604535148:ios:60f721dfd0a30ba84ae749',
    messagingSenderId: '746604535148',
    projectId: 'flordle-tpsi2526',
    storageBucket: 'flordle-tpsi2526.firebasestorage.app',
    iosBundleId: 'com.example.projetoProgMobileWordle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUohPXLMt25O1U7Kfc8xf2MwYZC1zqCl0',
    appId: '1:746604535148:web:6833f0eee3aecc4a4ae749',
    messagingSenderId: '746604535148',
    projectId: 'flordle-tpsi2526',
    authDomain: 'flordle-tpsi2526.firebaseapp.com',
    storageBucket: 'flordle-tpsi2526.firebasestorage.app',
    measurementId: 'G-302LEVTR4K',
  );
}
